services:
  - type: web
    name: real-estate-dashboard
    env: python
    plan: free        # hoặc starter nếu muốn mạnh hơn (2GB RAM)
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: PYSPARK_SUBMIT_ARGS
        value: "--master local[1] pyspark-shell"
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-17-openjdk-amd64"
